SiteConfig:
  extensions:
    - NewsletterSiteConfig
Controller:
  extensions:
    - NewsletterContentControllerExtension
Director:
  rules:
    'newsletterlinks/$Hash': 'TrackLinkController'
    'unsubscribe//$Action/$ValidateHash/$IDs': 'UnsubscribeController'
